### ISSUE TITLE
extension not compatible on Asus Chromebook Tab 10?

### ISSUE THREAD

**Issue by RJVB** [hickford/all-xkb-layouts#1]
Hi,

Any idea why the Google extensions store thinks this extension is  incompatible with my Asus CT100 CHromeBook Tab 10?

**Comment by hickford** [comment]
Hi René. No idea. What error message do you see?

Also, which version of Chrome OS are you using? 

Me (Settings / About Chrome OS / Additional details / Build details):

> Google Chrome: Version 94.0.4606.124 (Official Build)  (64-bit)
Platform: 14150.87.0 (Official Build) stable-channel hatch
Channel: stable-channel
Firmware Version: Google_Jinlon.12672.400.0
ARC enabled: false
ARC: 7888845
Enterprise enrolled: true
Developer mode: false

**Comment by hickford** [comment]
You could try installing the extension from source "load unpacked" https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest  or the .crx file in the zip attached 
[eogbkpghmlfbjmcanfcfbcnjlmhflbej_main.zip](https://github.com/hickford/xkb-keyboard-layouts-for-chrome-os/files/7601510/eogbkpghmlfbjmcanfcfbcnjlmhflbej_main.zip)

**Comment by RJVB** [comment]
I'm a bit confused, and sorry for the noise.

I got my device yesterday, and only tried to install your extension after I thought I'd given the thing more than enough time to install the latest updates. Turns out I was wrong; it was only after I created this ticket that I started getting a series of upgrade invitations.

It's working now. Or it would, if my onscreen keyboard showed a right Alt key (which I'd need for the "us(mac)" keymap).

Also, I like how this keymap deactivates the suggestion feature. It would be even better if it didn't reserve any space for that ... and if it somehow supported the new bordered rendering feature that makes using the keyboard a *LOT* easier. As in, you can actually almost type on it rather than pushing keys one at a time in order to hit the right one.

Off topic, but you wouldn't happen to know of an onscreen keyboard replacement that has iOS style support for entering accented characters, i.e. by holding the corresponding character key (e.g. holding "e" pops up a list of accented versions, é, è, ë etc)? Not having that is the kind of detail that could make me regret thinking a "ChromeTab" would be a practical alternative for an iPad...
