### ISSUE TITLE
Request for the addition of Santali (Ol Chiki) layout

### ISSUE THREAD

**Issue by Prasanta-Hembram** [hickford/all-xkb-layouts#3]
Hi, i request for the addition of Santali (Ol Chiki layout) :
Sarjom Baha: https://www.mediawiki.org/wiki/Help:Extension:UniversalLanguageSelector/Input_methods/sat-Sarjom_baha
Inscript: https://www.mediawiki.org/wiki/Help:Extension:UniversalLanguageSelector/Input_methods/sat-InScript2

**Comment by hickford** [comment]
Hi. Have you tried "XKB's in(olck) -- Ol Chiki" ([screenshot](https://user-images.githubusercontent.com/105314/150009452-ba07efac-8896-40fb-aabf-5623cd876202.png))?

**Comment by Prasanta-Hembram** [comment]
Thanks @hickford for the reply, i have already used that but i have a habit of using the Sarjom baha keyboard layout. May i know can we add additional layout to the extention or where work need to be done to add additional keyboard.

**Comment by hickford** [comment]
My extension is based on Linux's XKB which has only that one layout https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/symbols/in

You can create a Chrome extension with a complete layout following https://github.com/google/extra-keyboards-for-chrome-os/blob/master/example/remap/README.md
