### ISSUE TITLE
Wrong allocation on fr(mac)

### ISSUE THREAD

**Issue by antro31** [hickford/all-xkb-layouts#5]
Hello,
I have installed ChromeOS Flex on an old iMac with a French Keyboard. 
I also add installed your extension since I was not able to get the '@" working properly. 
Your extension works fine but with one exception though:
- Key ("@ #") is inverted with "< >". 

Do you think you can correct this?

**Comment by hickford** [comment]
Alas probably not -- this extension simply "unlocks" hidden layouts, it doesn't define them, so I can't make changes.
